### PR TITLE
Bug 1936871: allow setting a custom config for the driver

### PR DESCRIPTION
**Pull request by Fedosin**
This patch allows users to set custom config for the driver. To do so, they need to create a config map called "openstack-cinder-custom-config" in "openshift-cluster-csi-drivers" namespace, with a key "cloud.conf".

If this config map exists, then the driver will use the custom config.

### CODE REVIEW

**Review by mandre — COMMENTED** [review]
I'm not very keen on changing the default config, but according to the [ignore-volume-az documentation](https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/cinder-csi-plugin/using-cinder-csi-plugin.md#block-storage) the volume node affinity effectively prevents attaching to the node if the compute zone doesn't match the volume one _when_ Topology feature is turned on (that's the case for openshift).

@jsafrane is there a way to update the csi driver config as day2 similarly to what we're doing for the in-tree cinder provisioner? I'd prefer that if that was an option.

**Comment by jsafrane** [comment]
In-tree volume plugin seems to be controller by ConfigMap  `cloud-provider-config` in `openshift-config`. https://github.com/openshift/installer/blob/master/docs/user/openstack/known-issues.md#cinder-availability-zones

The Cinder operator should watch this ConfigMap and update Deployment/DaemonSet accordingly via DeploymentHook / DaemonSetHook, see e.g. [how AWS EBS operator modifies Deployment to inject optional CA bundle into Deployment](https://github.com/openshift/aws-ebs-csi-driver-operator/blob/97f73eb7de4b474497169771239dcd81990d3f2e/pkg/operator/starter.go#L155) )

**Review by mdbooth — CHANGES_REQUESTED** [review]
I'm uncomfortable with this change. As currently designed it could be improved as noted in review comments by:

* changing the configmap which we pass to the deployment rather than passing a second one
* refactoring the 2 podspec mutating methods to use common code

However, I'm more generally uncomfortable with the design of the feature.

It requires the user to pass in our default configuration in addition to any new configuration they want to add. This presents us with an incredibly messy upgrade problem if we ever need to change this.

It requires the user to pass in raw configuration at all. Can we not add an operator parameter which would set this, for eg?

If we decide to go with the user passing in config, please can we have them pass in an ini fragment which is merged with and overrides the default configuration? We should note in the documentation that they should not include any configuration directives that they don't want to override. In this way they could pass in simply:

```
[BlockStorage]
ignore-volume-az = true
```

rather than

```
[Global]
use-clouds = true
clouds-file = /etc/kubernetes/secret/clouds.yaml
cloud = openstack

[BlockStorage]
ignore-volume-az = true
```

/hold

**Comment by mdbooth** [comment]
I discussed this with @mandre earlier and we both have the same concern about the upgrade issue if we force the user to fork our default configuration.

We discussed the possibility of having some operator config which would write a new config itself containing `ignore-volume-az = true`. Neither of us were a huge fan of that, myself for many of the reasons I don't like TripleO. However, we did discuss it.

The 2 options we discussed for merging a default configuration with a user-supplied additional config were:

* Adding a tool to do this to the operator image, and then using this in an init container in the CSI controller pod
* Adding support to the CPO controller to take multiple configfile command line arguments, and merge them

Either of these would work for me as they both avoid the upgrade problem which is the real issue here. I personally prefer the latter as it would be cleaner, so I'm going to see if I can write that and propose it against upstream CPO on Monday. If we had that we'd just need some tweaks to this PR to add the second configfile to the command line in addition to the changes it already makes.

**Pull request closed without merging**
