### PR TITLE
Initial code for operator

### PR DESCRIPTION
**Pull request by bertinatto**
@Fedosin 

I took the code I had in https://github.com/bertinatto/openstack-cinder-csi-driver-operator-migrated and:

1. Updated library-go to latest version
2. Updated `starter.go` to use the new version of library-go
3. Updated a few other files, like Dockerfiles, Makefile etc.

TODO:

- [ ] Add `manifests` dir (AWS EBS operator can be use as an example)
- [ ] Replace upstream images by the downstream ones
- [ ] Update controller.yaml secret
- [ ] Update OWNERS file

CC @openshift/storage

### CODE REVIEW

**Review by Fedosin — APPROVED** [review]
/lgtm

**Comment by jsafrane** [comment]
/hold
For the automation to be enabled.

In addition, master is still 4.6, should this be merged?

**Comment by Fedosin** [comment]
it's okay to have this code in 4.6, since the operator is not integrated with CSO and OpenShift. When 4.7 master is open we will propose a patch to CSO to start deploying the operator during the installation.

Initial CI for this repo: https://github.com/openshift/release/pull/11779

**Comment by jsafrane** [comment]
Hmm, needs a valid bug label and OWNERS file. Merging manually.

**Pull request merged**
