### PR TITLE
Use go:embed for static yaml files

### PR DESCRIPTION
**Pull request by jsafrane**
Move from bindata to go:embed.

Contains bump of library-go and related changes.

### CODE REVIEW

**Comment by jsafrane** [comment]
/hold
for https://github.com/openshift/library-go/pull/1117

**Comment by jsafrane** [comment]
/hold cancel
updated with openshift/library-go#1117

**Comment by Fedosin** [comment]
isn't this PR a duplicate of https://github.com/openshift/openstack-cinder-csi-driver-operator/pull/42

**Pull request closed without merging**
