### PR TITLE
Bug 1902545: Only run driver-node on Linux workers

### PR DESCRIPTION
**Pull request by mdbooth**

### CODE REVIEW

**Review by Fedosin — CHANGES_REQUESTED** [review]
.csi_driver_node_service_controller.go.swp  should be removed

**Comment by Fedosin** [comment]
you also need to execute `make update-bindata` to include your changes in the generated go file.

**Comment by mdbooth** [comment]
@Fedosin 🤦‍♂️ and Done respectively. Thanks!

**Review by Fedosin — APPROVED** [review]
/lgtm

**Review by mandre — APPROVED** [review]
/lgtm
We need approval from someone from the storage team.
@bertinatto or @gnufied, this should be good to go I think.

**Review by bertinatto — COMMENTED** [review]
/lgtm
Thanks!

**Pull request merged**
