### PR TITLE
Bug 1909136: Pass cluster ID to CSI driver

### PR DESCRIPTION
**Pull request by Fedosin**
The CSI driver will add to the provisioned volumes the metadata needed to delete the volumes once the cluster is destroyed.

### CODE REVIEW

**Comment by mandre** [comment]
Please reference https://bugzilla.redhat.com/show_bug.cgi?id=1909136

**Comment by mdbooth** [comment]
Do we need to address PVs that already exist? i.e. the upgrade issue.

Is there anywhere in an operator where we could add an upgrade task? I guess this could be handled as a follow-on, btw, and could potentially be common with the manila fix.

**Comment by Fedosin** [comment]
@mdbooth I'm afraid we can't... There is no way to modify existing volumes using the csi controller, and OpenShift also doesn't provide any means for that.

**Review by mandre — COMMENTED** [review]
/lgtm
/hold pending openstack-e2e results and resolving Matt's question about fixing existing volumes.

**Comment by mdbooth** [comment]
@mandre Please don't hold for me. I think this change should merge with or without an upgrade fix.

**Pull request merged**
