### PR TITLE
STOR-947: support disabling default StorageClass via ClusterCSIDriver

### PR DESCRIPTION
**Pull request by dobsonj**
https://issues.redhat.com/browse/STOR-947
Marking this WIP until openshift/library-go#1441 merges.
/cc @openshift/storage

### CODE REVIEW

**Comment by dobsonj** [comment]
/retitle STOR-947: support disabling default StorageClass via ClusterCSIDriver

**Comment by jsafrane** [comment]
This failed:

> The Openstack platform should create an UDP Amphora LoadBalancer when an UDP svc with type:LoadBalancer is created on Openshift 

/retest

**Comment by ropatil010** [comment]
Payload: 4.13.0-0.ci-2023-01-26-131032

Test Results: 
###################test0_Default started #################
oc get clustercsidriver cinder.csi.openstack.org -o yaml | grep 'storageClassState'

oc get sc
NAME                     PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
csi-manila-ceph          manila.csi.openstack.org   Delete          Immediate              false                  105m
standard-csi (default)   cinder.csi.openstack.org   Delete          WaitForFirstConsumer   true                   106m

 change standard-csi volumeBindingMode
 change standard-csi reclaimPolicy
 change csi-manila-ceph volumeBindingMode
 change csi-manila-ceph reclaimPolicy

 Bydefault test change standard-csi allowVolumeExpansion to false
storageclass.storage.k8s.io/standard-csi patched
 Bydefault result oc get sc standard-csi
NAME   PROVISIONER   RECLAIMPOLICY        VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
standard-csi (default)   cinder.csi.openstack.org   Delete                       WaitForFirstConsumer   true                   106m

 Bydefault test change csi-manila-ceph allowVolumeExpansion to true
storageclass.storage.k8s.io/csi-manila-ceph patched
 Bydefault result oc get sc csi-manila-ceph
NAME              PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
csi-manila-ceph   manila.csi.openstack.org   Delete          Immediate           false                  105m

oc get sc
NAME    PROVISIONER   RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
csi-manila-ceph          manila.csi.openstack.org   Delete          Immediate              false                  105m
standard-csi (default)   cinder.csi.openstack.org   Delete          WaitForFirstConsumer   true                   106m

oc delete sc
storageclass.storage.k8s.io "csi-manila-ceph" deleted
storageclass.storage.k8s.io "standard-csi" deleted

oc get sc
NAME     PROVISIONER   RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
csi-manila-ceph          manila.csi.openstack.org   Delete          Immediate              false                  2s
standard-csi (default)   cinder.csi.openstack.org   Delete          WaitForFirstConsumer   true                   1s
###################test1_Removed started #################
oc get clustercsidriver cinder.csi.openstack.org -o yaml | grep 'storageClassState'
  storageClassState: Removed

 Removed test change standard-csi allowVolumeExpansion to false
 Removed test change csi-manila-ceph allowVolumeExpansion to true
storageclass.storage.k8s.io/csi-manila-ceph patched

 Removed result oc get sc
NAME              PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
csi-manila-ceph   manila.csi.openstack.org   Delete          Immediate           false                  2m42s
###################test2_Managed started #################
oc get clustercsidriver cinder.csi.openstack.org -o yaml | grep 'storageClassState'
  storageClassState: Managed

oc get sc
NAME                     PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
csi-manila-ceph          manila.csi.openstack.org   Delete          Immediate              false                  3m51s
standard-csi (default)   cinder.csi.openstack.org   Delete          WaitForFirstConsumer   true                   16s

 change standard-csi volumeBindingMode
 change standard-csi reclaimPolicy
 change csi-manila-ceph volumeBindingMode
 change csi-manila-ceph reclaimPolicy

 Bydefault test change standard-csi allowVolumeExpansion to false
storageclass.storage.k8s.io/standard-csi patched
 Bydefault result oc get sc standard-csi
NAME                     PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
standard-csi (default)   cinder.csi.openstack.org   Delete          WaitForFirstConsumer   true                   26s

 Bydefault test change csi-manila-ceph allowVolumeExpansion to true
storageclass.storage.k8s.io/csi-manila-ceph patched
 Bydefault result oc get sc csi-manila-ceph
NAME              PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
csi-manila-ceph   manila.csi.openstack.org   Delete          Immediate           false                  4m4s

oc get sc
NAME                     PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
csi-manila-ceph          manila.csi.openstack.org   Delete          Immediate              false                  4m5s
standard-csi (default)   cinder.csi.openstack.org   Delete          WaitForFirstConsumer   true                   30s

oc delete sc
storageclass.storage.k8s.io "csi-manila-ceph" deleted
storageclass.storage.k8s.io "standard-csi" deleted

oc get sc
NAME                     PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
csi-manila-ceph          manila.csi.openstack.org   Delete          Immediate              false                  3s
standard-csi (default)   cinder.csi.openstack.org   Delete          WaitForFirstConsumer   true                   2s
###################test3_Unmanaged started #################
oc get clustercsidriver cinder.csi.openstack.org -o yaml | grep 'storageClassState'
  storageClassState: Unmanaged

oc get sc
NAME                     PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
csi-manila-ceph          manila.csi.openstack.org   Delete          Immediate              false                  25m
standard-csi (default)   cinder.csi.openstack.org   Delete          WaitForFirstConsumer   true                   25m

 change standard-csi volumeBindingMode
 change standard-csi reclaimPolicy
 change csi-manila-ceph volumeBindingMode
 change csi-manila-ceph reclaimPolicy

 Unmanaged test change standard-csi allowVolumeExpansion to false
storageclass.storage.k8s.io/standard-csi patched
 Unmanaged result oc get sc standard-csi
NAME                     PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
standard-csi (default)   cinder.csi.openstack.org   Delete          WaitForFirstConsumer   false                  25m

 Unmanaged test change csi-manila-ceph allowVolumeExpansion to true
storageclass.storage.k8s.io/csi-manila-ceph patched
 Unmanaged result oc get sc csi-manila-ceph
NAME              PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
csi-manila-ceph   manila.csi.openstack.org   Delete          Immediate           false                  25m

oc get sc
NAME                     PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
csi-manila-ceph          manila.csi.openstack.org   Delete          Immediate              false                  25m
standard-csi (default)   cinder.csi.openstack.org   Delete          WaitForFirstConsumer   false                  25m

oc delete sc
storageclass.storage.k8s.io "csi-manila-ceph" deleted
storageclass.storage.k8s.io "standard-csi" deleted

oc get sc
NAME              PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
csi-manila-ceph   manila.csi.openstack.org   Delete          Immediate           false                  6s
###################test4a_Multiple Managed default sc started #################
oc get clustercsidriver cinder.csi.openstack.org -o yaml | grep 'storageClassState'
  storageClassState: Managed

oc get sc
NAME                     PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
csi-manila-ceph          manila.csi.openstack.org   Delete          Immediate              false                  15m
standard-csi (default)   cinder.csi.openstack.org   Delete          WaitForFirstConsumer   true                   8m55s
Creating sc
storageclass.storage.k8s.io/testsc created
Applying patch to sc testsc for changing to default
storageclass.storage.k8s.io/testsc patched

oc get sc
NAME                     PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
csi-manila-ceph          manila.csi.openstack.org   Delete          Immediate              false                  15m
standard-csi (default)   cinder.csi.openstack.org   Delete          WaitForFirstConsumer   true                   8m59s
testsc (default)         cinder.csi.openstack.org   Delete          WaitForFirstConsumer   true                   2s
###################test4b_Removed started #################
oc get clustercsidriver cinder.csi.openstack.org -o yaml | grep 'storageClassState'
  storageClassState: Removed

oc get sc and check standard-csi, , csi-manila-ceph should not be there and testsc should be there
NAME               PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
csi-manila-ceph    manila.csi.openstack.org   Delete          Immediate              false                  17m
testsc (default)   cinder.csi.openstack.org   Delete          WaitForFirstConsumer   true                   102s
###################test4c_Managed sc started #################
oc get clustercsidriver cinder.csi.openstack.org -o yaml | grep 'storageClassState'
  storageClassState: Managed

oc get sc all should be present now csi-manila-ceph, standard-csi, testsc
NAME               PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
csi-manila-ceph    manila.csi.openstack.org   Delete          Immediate              false                  20m
standard-csi       cinder.csi.openstack.org   Delete          WaitForFirstConsumer   true                   2m11s
testsc (default)   cinder.csi.openstack.org   Delete          WaitForFirstConsumer   true                   4m48s
Deleting all sc
storageclass.storage.k8s.io "testsc" deleted
storageclass.storage.k8s.io "csi-manila-ceph" deleted
storageclass.storage.k8s.io "standard-csi" deleted

oc get sc standard-csi and csi-manila-ceph should be back to default
NAME                     PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
csi-manila-ceph          manila.csi.openstack.org   Delete          Immediate              false                  3s
standard-csi (default)   cinder.csi.openstack.org   Delete          WaitForFirstConsumer   true                   2s
###################test5a_Managed default sc started #################
oc get clustercsidriver cinder.csi.openstack.org -o yaml | grep 'storageClassState'
  storageClassState: Managed

oc get sc
NAME                     PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
csi-manila-ceph          manila.csi.openstack.org   Delete          Immediate              false                  3m33s
standard-csi (default)   cinder.csi.openstack.org   Delete          WaitForFirstConsumer   true                   3m32s
###################test5b_Unmanaged default sc started #################
oc get clustercsidriver cinder.csi.openstack.org -o yaml | grep 'storageClassState'
  storageClassState: Unmanaged

oc get sc
NAME                     PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
csi-manila-ceph          manila.csi.openstack.org   Delete          Immediate              false                  5m55s
standard-csi (default)   cinder.csi.openstack.org   Delete          WaitForFirstConsumer   true                   5m54s
Creating sc
storageclass.storage.k8s.io/testsc created
Applying patch to sc testsc for changing to default
storageclass.storage.k8s.io/testsc patched
Applying patch to sc standard-csi for changing to non default
storageclass.storage.k8s.io/standard-csi patched

oc get sc
NAME               PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
csi-manila-ceph    manila.csi.openstack.org   Delete          Immediate              false                  6m1s
standard-csi       cinder.csi.openstack.org   Delete          WaitForFirstConsumer   true                   6m
testsc (default)   cinder.csi.openstack.org   Delete          WaitForFirstConsumer   true                   5s
###################test5c_Removed sc started #################
oc get clustercsidriver cinder.csi.openstack.org -o yaml | grep 'storageClassState'
  storageClassState: Removed

oc get sc standard-csi should not be there, csi-manila-ceph testsc should be there
NAME               PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
csi-manila-ceph    manila.csi.openstack.org   Delete          Immediate              false                  13m
testsc (default)   cinder.csi.openstack.org   Delete          WaitForFirstConsumer   true                   7m24s
Deleting sc testsc
storageclass.storage.k8s.io "testsc" deleted
Deleting sc csi-manila-ceph
storageclass.storage.k8s.io "csi-manila-ceph" deleted
Deleting sc standard-csi

oc get sc
NAME              PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
csi-manila-ceph   manila.csi.openstack.org   Delete          Immediate           false                  6s

**Pull request merged**
