### PR TITLE
Bug 1989215: [openstack-cinder-csi-driver-operator] csi-liveness-probe is not deployed

### PR DESCRIPTION
**Pull request by dobsonj**
https://bugzilla.redhat.com/show_bug.cgi?id=1989215
cc @openshift/storage

### CODE REVIEW

**Comment by dobsonj** [comment]
/hold
while debugging test failures

**Comment by jsafrane** [comment]
From https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_openstack-cinder-csi-driver-operator/52/pull-ci-openshift-openstack-cinder-csi-driver-operator-master-e2e-openstack-csi/1422668750364086272/artifacts/e2e-openstack-csi/gather-extra/artifacts/clusteroperators.json:

```
            "status": {
                "conditions": [
                    {
                        "lastTransitionTime": "2021-08-03T22:33:01Z",
                        "message": "OpenStackCinderCSIDriverOperatorCRDegraded: OpenStackCinderDriverNodeServiceControllerDegraded: DaemonSet.apps \"openstack-cinder-csi-driver-node\" is invalid: spec.template.spec.containers[2].volumeMounts[0].name: Not found: \"plugin-dir\"",
                        "reason": "OpenStackCinderCSIDriverOperatorCR_OpenStackCinderDriverNodeServiceController_SyncError",
                        "status": "True",
                        "type": "Degraded"
                    },
```

**Comment by dobsonj** [comment]
>                         "message": "OpenStackCinderCSIDriverOperatorCRDegraded: OpenStackCinderDriverNodeServiceControllerDegraded: DaemonSet.apps \"openstack-cinder-csi-driver-node\" is invalid: spec.template.spec.containers[2].volumeMounts[0].name: Not found: \"plugin-dir\"",

Oops! Thanks for pointing this out.

**Pull request merged**
