### PR TITLE
Bug OCPBUGS-2845: Add SecretHashAnnotation to node service

### PR DESCRIPTION
**Pull request by mdbooth**
Ensure node service is updated if the credentials secret is changed.

### CODE REVIEW

**Comment by MaysaMacedo** [comment]
/retest-required

So I can access mecha and check what is happening with the load-balancer

**Comment by MaysaMacedo** [comment]
/retest-required
I updated the lb-network MTU, let's see if it helps

**Comment by dulek** [comment]
/cherry-pick release-4.12

Why haven't we did that already…?

**Pull request merged**
