### PR TITLE
Bug 1952211: Fix error when mounting /var/lib/kubelet/pods

### PR DESCRIPTION
**Pull request by Fedosin**
Downstream update to comply with https://github.com/kubernetes/cloud-provider-openstack/pull/773

### CODE REVIEW

**Review by mdbooth — CHANGES_REQUESTED** [review]
~~Please can you replace this with a 'cherry-pick -x' of the upstream commit?~~

Nm, the source commit is from a different repo. We're just copying a change in the upstream manifests to the operator which deploys it.

**Review by mdbooth — APPROVED** [review]
/lgtm

We're just staying in sync with the upstream manifests.

I'm disappointed at the lack of information in the upstream commit, though.

**Comment by zerodayz** [comment]
Manually resolved conflicts and created new PR https://github.com/openshift/openstack-cinder-csi-driver-operator/pull/61

**Pull request merged**
