### PR TITLE
Bug 1905849: create default VolumeSnapshotClass

### PR DESCRIPTION
**Pull request by Fedosin**
Now it's not possible to make volume snapshots right after installation, because there are no VolumeSnapshotClasses in the system.

This commit allows the operator to generate a default VolumeSnapshotClass along with the driver provisioning.

### CODE REVIEW

**Comment by mdbooth** [comment]
Looks good, but I think we need some test coverage. Either an integrated functional test, or inclusion of a volumesnapshot test in, e.g. e2e-openstack. Do we have that already? If not, how can we add it?

**Comment by Fedosin** [comment]
@mdbooth unit tests are implmented in library-go: https://github.com/openshift/library-go/blob/master/pkg/operator/resource/resourceapply/volumesnapshotclass_test.go
For functional tests we need a csi workflow that is implemented here: https://github.com/openshift/release/pull/14243

**Pull request merged**
