### PR TITLE
[release-4.13] OCPBUGS-16250: Add management workloads annotations

### PR DESCRIPTION
**Pull request by Phaow**
This is a manual cherry-pick of https://github.com/openshift/openstack-cinder-csi-driver-operator/pull/109 , fix the OCPBUGS-16250.

### CODE REVIEW

**Comment by stephenfin** [comment]
/retest-required

checksum issues in CI

**Comment by Phaow** [comment]
@stephenfin All the tests passed, could you please help take a look again? Thanks!

**Comment by Phaow** [comment]
@mandre Could you please take a look and add the `backport-risk-assessed` label ? Thanks in advance!

**Comment by Phaow** [comment]
@itzikb-redhat Could you please take a look and add the `cherry-pick-approved` label ? Thanks in advance!

**Pull request merged**
