### PR TITLE
Enable topology support

### PR DESCRIPTION
**Pull request by Fedosin**
According to the documentation Cinder CSI driver supports Topology feature[1].

This commit enables the feature for the external provisioner.

[1] https://github.com/kubernetes/cloud-provider-openstack/blob/master/docs/cinder-csi-plugin/features.md#topology

### CODE REVIEW

**Comment by jsafrane** [comment]
/lgtm
/hold
feel free to un-hold when a CI cluster installs

**Comment by Fedosin** [comment]
/hold cancel

I'm removing hold, I believe this is safe for this patch. Next week we will implement a proper e2e job to test Topology feature.

**Pull request merged**
