### PR TITLE
Bug 2038053: Bump k8s to 1.23

### PR DESCRIPTION
**Pull request by mandre**
This is the result of:
```
go get github.com/openshift/api@7c47a5f
go get github.com/openshift/client-go@7385dd6
go get github.com/openshift/library-go@624c91f
go get k8s.io/component-base@969bfa2
go mod vendor
go mod tidy
```

### CODE REVIEW

**Comment by pierreprinetti** [comment]
You are missing apiserver. Try:

```
go get k8s.io/apiserver
```

**Comment by mandre** [comment]
> You are missing apiserver. Try:
> 
> ```
> go get k8s.io/apiserver
> ```

Thanks, I forgot to bump library-go, and doing it pulled apiserver. This should be good now :crossed_fingers:

**Comment by mandre** [comment]
Cinder CSI driver operator fails to start:
```
2022-01-06T13:28:00.172812637Z Error: unknown shorthand flag: 'v' in -v=2
2022-01-06T13:28:00.172812637Z Usage:
2022-01-06T13:28:00.172812637Z   openstack-cinder-csi-driver-operator start [flags]
2022-01-06T13:28:00.172812637Z 
2022-01-06T13:28:00.172812637Z Flags:
2022-01-06T13:28:00.172812637Z       --config string                    Location of the master configuration file to run from.
2022-01-06T13:28:00.172812637Z   -h, --help                             help for start
2022-01-06T13:28:00.172812637Z       --kubeconfig string                Location of the master configuration file to run from.
2022-01-06T13:28:00.172812637Z       --listen string                    The ip:port to serve on.
2022-01-06T13:28:00.172812637Z       --namespace string                 Namespace where the controller is running. Auto-detected if run in cluster.
2022-01-06T13:28:00.172812637Z       --terminate-on-files stringArray   A list of files. If one of them changes, the process will terminate.
2022-01-06T13:28:00.172812637Z 
2022-01-06T13:28:00.172812637Z unknown shorthand flag: 'v' in -v=2
```

**Comment by mandre** [comment]
The `-v=2` option comes from https://github.com/openshift/cluster-storage-operator/blob/b89dad1/assets/csidriveroperators/openstack-cinder/07_deployment.yaml#L24.

**Comment by mandre** [comment]
This is ready, the snapshot errors in the CSI job are expected and will go away once we move the job to vh-mecha (https://github.com/openshift/release/pull/24455).

**Comment by pierreprinetti** [comment]
/hold 
see https://bugzilla.redhat.com/show_bug.cgi?id=2038166

**Comment by sdodson** [comment]
/hold
This also missed feature freeze. We need to discuss whether or not these make sense to land after feature freeze.

**Comment by pierreprinetti** [comment]
/hold cancel

Thank you @sdodson

**Pull request merged**
